spice_mix = set()
print(f"Initial spice mix: {id(spice_mix)}")
print(f"Initial spice mix contents: {spice_mix}")
spice_mix.add("Ginger") 
spice_mix.add("Cardamom") 
spice_mix.add("lemon grass")
print(f"Initial spice mix id: {id(spice_mix)}")
print(f"After adding spices: {id(spice_mix)}")
print(f"After adding spices contents: {spice_mix}")
